import math, statistics, time, sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.pipeline.orchestrator import PipelineOrchestrator

QUERIES = [
    "What is the chemical formula for water?",
    "Tallest building in Paris",
    "Where is the Eiffel Tower located?",
    "Explain the process of photosynthesis.",
    "Who is the current president of the United States?",
    "Tell me about the chemical formula for photosynthesis on Mars",
    "How do I bake a chocolate cake?",
    "fjkdlsafjkdslajfklsdajlk",
    "hi",
    "Water cycle",
]

REPEAT = 3
all_queries = QUERIES * REPEAT

orchestrator = PipelineOrchestrator()
# Warmup
try:
    orchestrator.process_query("What is photosynthesis?")
except Exception:
    pass

metrics = {
    "input_guard_ms": [],
    "embedding_ms": [],
    "retrieval_ms": [],
    "reranking_ms": [],
    "confidence_gate_ms": [],
    "rag_total_ms": [],
}

success = 0
rejects = 0

for q in all_queries:
    res = orchestrator.process_query(q)
    l = res.latency
    metrics["input_guard_ms"].append(l.input_guard_ms)
    metrics["rag_total_ms"].append(l.rag_total_ms)
    if l.embedding_ms > 0: metrics["embedding_ms"].append(l.embedding_ms)
    if l.retrieval_ms > 0: metrics["retrieval_ms"].append(l.retrieval_ms)
    if l.reranking_ms is not None and l.reranking_ms > 0: metrics["reranking_ms"].append(l.reranking_ms)
    if l.confidence_gate_ms > 0: metrics["confidence_gate_ms"].append(l.confidence_gate_ms)
    if res.rejected:
        rejects += 1
    else:
        success += 1

# percentile helper: p in [0,100] -> value

def percentile(arr, p):
    if not arr:
        return None
    arr = sorted(arr)
    if p >= 100:
        return arr[-1]
    k = (len(arr)-1) * (p/100.0)
    f = math.floor(k)
    c = math.ceil(k)
    if f == c:
        return arr[int(k)]
    d0 = arr[int(f)] * (c-k)
    d1 = arr[int(c)] * (k-f)
    return d0 + d1

out_lines = []
out_lines.append('# Latency benchmark report')
out_lines.append('')
out_lines.append(f'- Total queries: {len(all_queries)}')
out_lines.append(f'- Successful generations: {success}')
out_lines.append(f'- Early rejections: {rejects}')
out_lines.append('')

out_lines.append('## TOTAL RAG FLOW')
out_lines.append('')
out_lines.append('| Percentile | Latency (ms) |')
out_lines.append('| --- | ---: |')
for p in [50,70,100]:
    val = percentile(metrics['rag_total_ms'], p)
    out_lines.append(f'| P{p} | {val:.1f} |')

out_lines.append('')
out_lines.append('## Stage percentiles')
out_lines.append('')
out_lines.append('| Stage | P50 (ms) | P70 (ms) | P100 (ms) |')
out_lines.append('| --- | ---: | ---: | ---: |')
for name,key in [('Input Guard','input_guard_ms'),('Embedding','embedding_ms'),('Retrieval','retrieval_ms'),('Reranking','reranking_ms'),('Confidence Gate','confidence_gate_ms')]:
    vals = metrics[key]
    if not vals:
        out_lines.append(f'| {name} | N/A | N/A | N/A |')
    else:
        out_lines.append(f'| {name} | {percentile(vals,50):.1f} | {percentile(vals,70):.1f} | {percentile(vals,100):.1f} |')

out_lines.append('')
out_lines.append('Generated by scripts/generate_latency_report.py')

with open('result.md','w') as f:
    f.write('\n'.join(out_lines))

print('Wrote result.md')
